something = input('Escreva algo: ')
print('Tipo: {}'.format(type(something)))
print('Is Upper: {}'.format(something.isupper()))
print('Is Lower: {}'.format(something.islower()))
print('Is Digit: {}'.format(something.isdigit()))
print('Is Decimal: {}'.format(something.isdecimal()))
print('Is Alpha: {}'.format(something.isalpha()))
print('Is Numeric: {}'.format(something.isnumeric()))
print('Is AlfaNumeric: {}'.format(something.isalnum()))
print('Is Printable: {}'.format(something.isprintable()))
print('Is Space: {}'.format(something.isspace()))